//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 10 23:24:40 EST 2019
//----------------------------------------------------
package CompiladorHTML;

/**
 * CUP generated class containing symbol constants.
 */
public class sym {

    /* terminals */
    public static final int comilla = 15;
    public static final int number = 5;
    public static final int texto = 19;
    public static final int type = 3;
    public static final int lista = 10;
    public static final int num = 22;
    public static final int h1 = 21;
    public static final int label = 20;
    public static final int input = 2;
    public static final int radio = 7;
    public static final int menor = 13;
    public static final int text = 4;
    public static final int option = 11;
    public static final int checkbox = 8;
    public static final int igual = 16;
    public static final int EOF = 0;
    public static final int division = 14;
    public static final int id = 18;
    public static final int min = 23;
    public static final int error = 1;
    public static final int max = 24;
    public static final int maxlength = 25;
    public static final int date = 6;
    public static final int coments = 9;
    public static final int name = 17;
    public static final int mayor = 12;
}
